name: format lint and test script
on:
    push
jobs:
  format-lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
      - name: install project dependencies
        run: uv sync --dev
      - name: Type check all files
        run: uv run ty check .
      - name: Lint check all files
        run: uv run ruff check .

  run-unittests:
    needs: format-lint
    runs-on: ubuntu-latest
    steps:
        - name: checkout code
          uses: actions/checkout@v6
        - name: Install the latest version of uv
          uses: astral-sh/setup-uv@v7
        - name: install project dependencies
          run: uv sync
        - name: run tests
          run: uv run python -m unittest discover tests
